import { Capacitor } from '@capacitor/core';
import * as axiosClient from './axiosClient';
import * as capacitorClient from './capacitorClient';

const client = Capacitor.isNativePlatform() ? capacitorClient : axiosClient;

export const {
  createOrganization,
  logIn,
  logOut,
  verifyCurrentUser,
  receiveProducts,
  createUser,
  createWarehouse,
  createGrainType,
  createSupplier,
  createQaData,
  createBatch,
  createFumigation,
  addFirstMass,
  addSecondMass,
  addDailyProduction,
  addOrder,
  addReceivedStock,
  updateQaData,
  pickOrder,
  getBranches,
  getCurrentUser,
  getSuppliers,
  getGrainTypes,
  getReceivedProduce,
  getPendingFirstMass,
  getPendingSecondMass,
  getPendingQA,
  getCommodityReceipts,
  getSilos,
  getReceivedProduceTrends,
  getDailyProduction,
  getReceivedVsProducedTrend,
  getProductionTrends,
  getUserAccounts,
  getStockIn,
  getStock,
  getStockOut,
  getOrders,
  getBatches,
  getPendingOrders,
  getOrderPickingPlan,
} = client;
